version: 0.2
batch:
  fast-fail: false
  build-matrix:
    static:
      ignore-failure: false
      env:
        type: LINUX_CONTAINER
        privileged-mode: true
    dynamic:
      env:
        image:
          - public.ecr.aws/q6t8o9m1/cypress-browsers-node14.7.0-chrome84
        variables:
          MACHINE_NO:
            - 1
            - 2
            - 3
            - 4
            - 5
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm ci
  pre_build:
    commands:
      - npm run cy:verify
      - npm run cy:info
  build:
    commands:
      - npm run start:ci &
      - npx cypress run --record --parallel --browser chrome
