version: 0.2

# Batch configuration
#
batch:
  fast-fail: false
  build-matrix:
    static:
      ignore-failure: false
      env:
        type: LINUX_CONTAINER
        privileged-mode: true
    dynamic:
      env:
        image:
          - public.ecr.aws/q6t8o9m1/cypress-included-6-1-0
        variables:
          CYPRESS_SPEC:
            - cypress/integration/actions.spec.js
            #- cypress/integration/aliasing.spec.js
            #- cypress/integration/assertions.spec.js
            #- cypress/integration/connectors.spec.js
            #- cypress/integration/cookies.spec.js
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm ci
  pre_build:
    commands:
      - npm run cy:verify
      - npm run cy:info
      - echo $CYPRESS_SPEC
      - echo $CODEBUILD_SRC_DIR
      - echo ${CODEBUILD_SRC_DIR}/$CYPRESS_SPEC
      - export CY_SPEC=$($CODEBUILD_SRC_DIR/$CYPRESS_SPEC)
      - echo $CY_SPEC
  build:
    commands:
        - npm run start:ci &
        - npx cypress run --record --parallel --ci-build-id $CODEBUILD_INITIATOR --spec $CY_SPEC