version: 0.2

# Batch configuration
#
batch:
  fast-fail: false
  build-list:
    - identifier: cypress1
      env:
        variables:
          IMAGE: cypress/base
    - identifier: cypress2
      env:
        variables:
          IMAGE: cypress/base
    - identifier: cypress3
      env:
        variables:
          IMAGE: cypress/base

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
      - npm install wait-on
  pre_build:
    commands:
      - npm run build
  build:
    commands:
        - "npm start & npx wait-on http://127.0.0.1:8080"
        - npx cypress run --record --parallel --ci-build-id $CODEBUILD_SOURCE_VERSION