version: 0.2
batch:
  fast-fail: false
  build-matrix:
    static:
      ignore-failure: false
      env:
        type: LINUX_CONTAINER
        privileged-mode: true
    dynamic:
      env:
        image:
          - public.ecr.aws/q6t8o9m1/cypress-browsers-node14.7.0-chrome84
        variables:
          CYPRESS_SPEC:
            - cypress/integration/examples/actions.spec.js
            - cypress/integration/examples/aliasing.spec.js
            - cypress/integration/examples/assertions.spec.js
            - cypress/integration/examples/cookies.spec.js
            - cypress/integration/examples/connectors.spec.js
            - cypress/integration/examples/cypress_api.spec.js
            - cypress/integration/examples/files.spec.js
            - cypress/integration/examples/local_storage.spec.js
            - cypress/integration/examples/location.spec.js
            - cypress/integration/examples/navigation.spec.js
            - cypress/integration/examples/network_requests.spec.js
            - cypress/integration/examples/misc.spec.js
            - cypress/integration/examples/querying.spec.js
            - cypress/integration/examples/spies_stubs_clocks.spec.js
            - cypress/integration/examples/traversal.spec.js
            - cypress/integration/examples/utilities.spec.js
            - cypress/integration/examples/waiting.spec.js
            - cypress/integration/examples/viewport.spec.js
            - cypress/integration/examples/window.spec.js
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm ci
  pre_build:
    commands:
      - npm run cy:verify
      - npm run cy:info
  build:
    commands:
      - npm run start:ci &
      - npx cypress run --browser chrome --spec $CODEBUILD_SRC_DIR/$CYPRESS_SPEC
