version: 0.2

# Batch configuration
#
batch:
  fast-fail: false
  build-matrix:
    static:
      ignore-failure: false
      env:
        type: LINUX_CONTAINER
        privileged-mode: true
    dynamic:
      env:
        image:
          - public.ecr.aws/q6t8o9m1/cypress-included-6-1-0
        variables:
          CYPRESS_SPEC:
            - cypress/integration/examples/actions.spec.js
            - cypress/integration/examples/aliasing.spec.js
            - cypress/integration/examples/assertions.spec.js
            - cypress/integration/examples/connectors.spec.js
            - cypress/integration/examples/cookies.spec.js
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm ci
  pre_build:
    commands:
      - npm run cy:verify
      - npm run cy:info
  build:
    commands:
        - npm run start:ci &
        - npx cypress run --browser chrome --spec $CODEBUILD_SRC_DIR/$CYPRESS_SPEC
        #- npx cypress run --record --parallel --ci-build-id $CODEBUILD_INITIATOR --spec $CODEBUILD_SRC_DIR/$CYPRESS_SPEC